// examples/solidstart/src/components/Example.tsx
import { createResource, createSignal, Suspense } from 'solid-js';
import { fn$ } from 'thaler';
import { debounce } from 'thaler/utils';

async function sleep<T>(value: T, ms: number): Promise<T> {
  return new Promise<T>(res => {
    setTimeout(res, ms, value);
  });
}

export default function Example() {
  const [state, setState] = createSignal(0);

  const prefix = 'Server Count';

  const serverCount = debounce(
    fn$((value: number) => {
      console.log('Received', value);
      return {
        data: `${prefix}: ${value}`,
        delayed: sleep(`Delayed ${prefix}: ${value}`, 1000),
      };
    }),
    {
      key: () => 'sleep',
    },
  );

  const [data] = createResource(state, value => serverCount(value));

  function increment() {
    setState(c => c + 1);
  }

  return (
    <>
      <button onClick={increment}>{`Client Count: ${state()}`}</button>
      <div>
        <Suspense fallback={<h1>Loading</h1>}>
          <h1>{data()?.data}</h1>
        </Suspense>
      </div>
    </>
  );
}

// examples/sveltekit/src/components/Example.svelte
<script>
  import { fn$ } from "thaler";
  import { debounce } from "thaler/utils";

  const prefix = "Server Count";

  const serverCount = debounce(
    fn$((value) => {
      console.log("Received", value);
      return {
        data: `${prefix}: ${value}`,
        delayed: new Promise((res) => {
          setTimeout(res, 1000, `Delayed ${prefix}: ${value}`);
        }),
      };
    }),
    {
      key: () => "sleep",
    },
  );

  let state = 0;

  $: data = serverCount(state);

  function increment() {
    state += 1;
  }
</script>

<button on:click={increment}>
  {`Client Count: ${state}`}
</button>
<div>
  {#await data}
    <h1>Loading</h1>
  {:then value}
    <h1>{value.data}</h1>
    {#await value.delayed}
      <h1>Loading</h1>
    {:then delayed}
      <h1>Delayed: {delayed}</h1>
    {/await}
  {/await}
</div>
